mrc-ide/dust2

R/cpp11.R
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/walk.cpp
tests/testthat/test-walk.R

~Merge after #1, contains those commits~
I was going to be clever here, but it looks like the simplest thing actually works pretty well.  I was concerned that `t + n * dt` would eventually become non-integer-like for some `dt` because in general `1 / (1 / dt)` is not the same as `dt`. However, that's only practically an issue for things like `dt = 1/49` and this is close enough for now.
The ultimate issue is that when we consider data we need to make sure we land on exactly the right step, but I'll look at that another way when setting data I think

Allow fractional time

---

.Rbuildignore
R/cpp11.R
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/walk.cpp
tests/testthat/test-walk.R

~Merge after #3, contains those commits.~
This PR allows export of state as a multidimensional matrix.  The export code potentially fairly interesting, using the c++ initializer list in place of a variadic arg which is new to me, but seems to be fairly concise and easy to read.  We'll use this approach for saving the trajectories over time too.

Export state with dimension attribute

---

R/cpp11.R
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/walk.cpp
tests/testthat/test-walk.R

This PR allows us to reorder state among particles; this is one of the bits we need to support a particle filter and is rarely useful in its own right.  I've exposed a little helper for it for now at least though as it makes testing much easier.

Allow reordering state

---

inst/examples/sir.cpp
inst/include/dust2/common.hpp
inst/include/dust2/tools.hpp
tests/testthat/test-sir.R

Merge after #2, contains those commits
This PR adds a helper for accumulation of periodic incidence (e.g., case over a day).  It is stateless - in that it requires no additional state to be stored in the object - which makes it easy to use.  We'll need a better trick to do this for ODE models once we support those.

Allow periodic accumulation of variables

---

R/cpp11.R
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
src/cpp11.cpp
src/sir.cpp
src/walk.cpp
tests/testthat/test-sir.R
tests/testthat/test-walk.R

~Merge after #11, contains those commits~
This PR adds a higher-level run function that runs to a specific time, rather than a specific number of steps.  This is likely the interface that we'll use most of time, certainly for the user.  This interface will also improve readability of the particle filter PRs because we don't have to think so much in terms of steps (though this will be inevitable in some cases)

Run to time, rather than number of steps

---

R/cpp11.R
inst/include/dust2/filter.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/filter.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/sir.cpp
tests/testthat/test-filter.R

~Merge after #8, contains those commits~
This PR allows a filter run to use custom initial conditions, rather than those defined in the model

Allow setting initial state into filter

---

R/cpp11.R
inst/include/dust2/filter.hpp
inst/include/dust2/filter_details.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/filter.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/sir.cpp
src/test.cpp
tests/testthat/helper-dust.R
tests/testthat/test-filter-details.R
tests/testthat/test-filter.R

~Merge after #8, contains those commits~
We'll get better statistical tests on this later, but some poking about with it suggests we're correct :-/
For the future tests, we have a model where we derived the likelihood a different way and show it converges.  But for that I need to implement support for compiling models as we go, and that's a few PRs away.
This PR implements the same particle filter algorithm as used in dust1 and mcstate1:
1. advance the model up to the next data point
2. compare particles to the data
3. convert the log likelihoods into a set of weights (this requires moving out of the log basis into a normal basis, which is half of the gross bookkeeping - `scale_log_weights`)
4. resample using the "systematic sampling" scheme (this is the other half of gross bookkeeping, …

Compute likelihood via particle filter

---

R/cpp11.R
inst/include/dust2/history.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/test.cpp
tests/testthat/test-filter-details.R

Merge after #14, contains those commits (and that PR contains some context for this)
This PR contains a utility class for saving history.  We'll create one of these and tell it how many states the particles have, how many particles, groups and timesteps we want to save for.  Then we add states in with the `add` method.  In the case of the particle filter we'll also add in the particle ordering indicies (https://github.com/mrc-ide/dust2/blob/main/inst/include/dust2/filter.hpp#L143) so that we can reconstruct the tree of history.
The algorithm for doing this was worked out on paper a while ago, and is ported across here - see the tests to see that it works.  But the idea is that we don't resort the history itself, only the bits that are copied out on export.  To do this we start at the last …

Utility class for saving history

---

DESCRIPTION
R/metadata.R
R/util.R
inst/examples/sir.cpp
inst/examples/walk.cpp
inst/include/dust2/common.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/helpers.hpp
tests/testthat/test-metadata.R

This is the first stage of supporting compiling models; parsing some metadata out of the source code.  See the new attributes in `inst/examples/sir.cpp` and `examples/walk.cpp` for examples of this.
When we come to do code generation we will not attempt to parse C++ (which is hard) but instead inspect these attributes and generate code based on what we find.  This is what we ended up doing in dust1 eventually, it's much easier than trying to be clever, and practically it's not very hard to do because most models are generated mechanically anyway.
At the same time I've updated the parameter- and data-reading functions to use some common code, which provides much nicer error messages.
We'll probably expand some of the attribute support here, in particular advertising parameter types and if …

Parse attribute-style comments from source code

---

R/cpp11.R
R/interface.R
inst/examples/walk.cpp
inst/include/dust2/filter.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/filter.hpp
src/cpp11.cpp
src/sir.cpp
src/test.cpp
tests/testthat/helper-dust.R
tests/testthat/test-filter-details.R
tests/testthat/test-filter.R
tests/testthat/test-interface.R
tests/testthat/test-sir.R
tests/testthat/test-walk.R

* Small lint
* Various bits of missing coverage, one of which (for the filter details) required a new little helper test function
* Pass `initial` through to filter for consistency with the unfilter

Fix lint, coverage holes and trivial features

---

inst/examples/sir.cpp
inst/examples/walk.cpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/r/helpers.hpp
src/sir.cpp
src/walk.cpp

This is one of several bits that will help with the move to using ODE models as there we also have the size of output (derived quantities from state).  This way is less ambiguous in general

Use size_state in place of size

---

inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/errors.hpp
inst/include/dust2/r/system.hpp
tests/testthat/test-sir.R
tests/testthat/test-sirode.R

This is a necessary condition for openmp, because errors thrown in parallel blocks are efficiently converted into crashes!
The implementation here closely mirrors the one we used in dust1, though some of the details of reporting are slightly different.

Support for collecting then throwing errors

---

R/cpp11.R
R/interface.R
inst/include/dust2/r/system.hpp
inst/template/system.cpp
man/dust_system_state.Rd
src/cpp11.cpp
src/logistic.cpp
src/sir.cpp
src/sirode.cpp
src/walk.cpp
tests/testthat/test-walk.R

This PR allows `dust_system_state` to filter system state by state index, particle index or (in a grouped system) group index.  This will certainly be pulled into some sort of helper function at some point because this sort of filtering will turn up elsewhere (e.g., within the particle filter) and because it's surprisingly awkward.  This will also be the basis for the inteface at the R level of things like "run the filter just for these groups only" I think.

Allow filtering states on extraction

---

inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/r/continuous/system.hpp
inst/include/dust2/r/discrete/filter.hpp
inst/include/dust2/r/discrete/system.hpp
inst/include/dust2/r/discrete/unfilter.hpp
inst/include/dust2/r/helpers.hpp
inst/include/dust2/tools.hpp

This PR allocates an internals object per group per thread.  This is still fairly theoretical since we don't use internals much anywhere, but we'll want this in place once we are generating models from odin2.
~Merge after #46, as it contains those commits - it's impossible to avoid the fallout from that PR, really~

Allocate one internals per thread (per group)

---

R/check.R
R/filter-support.R
R/interface-filter.R
R/interface-unfilter.R
R/interface.R
inst/include/dust2/history.hpp
inst/include/dust2/r/filter.hpp
inst/include/dust2/r/unfilter.hpp
man/dust_filter_last_history.Rd
man/dust_filter_run.Rd
man/dust_unfilter_last_gradient.Rd
man/dust_unfilter_last_history.Rd
man/dust_unfilter_run.Rd
src/test.cpp
tests/testthat/test-filter-details.R
tests/testthat/test-filter-support.R
tests/testthat/test-filter.R
tests/testthat/test-unfilter.R

This PR builds on #49, allowing us to run a filter/unfilter for a subset of parameter groups.  The little test helper for history sorting did a lot of the heavy lifting and you should be able to see the effect in the tests.  Not too bad in the end!

Allow running a subset of groups in filter/unfilter

---

R/interface-unfilter.R
R/interface.R
R/mcstate.R
man/dust_unfilter_run.Rd
tests/testthat/test-mcstate.R
tests/testthat/test-unfilter-adjoint.R

Small but worth looking through - there's some unplesantness around the last_gradient bit, and I wonder if eventually we should move to a "density-with-gradient" interface for some of this?  I think the solution is ok, but I also think we can do better in future by pushing this logic into the C++ code.  For now it does the right thing at least.
Note that the behaviour of the 'adjoint' argument to running the unfilter has changed, along with the default.

Build mcstate interface for models with gradients

---

R/cpp11.R
R/interface-filter.R
R/test.R
R/util_assert.R
inst/include/dust2/filter.hpp
inst/include/dust2/history.hpp
inst/include/dust2/r/filter.hpp
inst/include/dust2/r/system.hpp
inst/include/dust2/r/unfilter.hpp
inst/template/compare.cpp
man/dust_filter_last_history.Rd
src/cpp11.cpp
src/sir.cpp
src/test.cpp
tests/testthat/test-filter-details.R
tests/testthat/test-filter.R

another tedious bit of bookkeeping.  this exists to support the idea of "give me a random history from each parameter group after running a particle filter".  This will be wired into a nice observer we can use with the models in the mcstate2 wrapper in a future PR

Select random  particle from filter

---

inst/examples/sir.cpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/r/discrete/filter.hpp
inst/include/dust2/r/discrete/unfilter.hpp
inst/include/dust2/r/helpers.hpp
inst/include/dust2/r/system.hpp
src/sir.cpp

This will require a small tweak in odin, I'll sort that out later.
This PR makes `shared` available while processing data, which we found we practically needed when working with Thom's model.  It is plausible that a suitably complicated version of data processing would require internal too, but I'm finding that hard to motivate

Pass shared when setting data

---

inst/include/dust2/zero.hpp
tests/testthat/examples/zerotwice.cpp
tests/testthat/test-zzz-slow.R

This was reported by Ed (see mrc-5641), and I've split the fix into odin2 and dust2.
We were storing reset times as a map which meant if two resets had the same interval only one made it through the constructor! We never actually use anything taking advantage of this being a mapping type so the fix is just to store as a vector of pairs.

Cope with multiple zero_every better

---

DESCRIPTION
R/cpp11.R
inst/include/dust2/interpolate/interpolate.hpp
src/cpp11.cpp
src/test_interpolate.cpp
tests/testthat/test-interpolate.R

This PR extends #58 to allow for interpolation of vectors of related things.  There's no covariance in the interpolation (this follows odin1), but you can have a matrix 'y' that is interpolated over time so that at each timestep we get a vector out.  This is done in-place rather than via return values.
There's a small fiddle in the validation code but otherwise this is just a loop at the interpolation step.  In the linear/spline case, we take advantage of some intermediate calculations that are shared over all the values at a given time.
The only real complication is the setup for spline interpolation, which is not very fun.

Allow multidimensional interpolation

---

inst/include/dust2/adjoint_data.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/unfilter.hpp
tests/testthat/test-interpolate.R

This PR does some housekeeping so that the unfilter is less tightly coupled to running with a discrete time model.  This moves the logic around moving around within the `state` vector into `adjoint_data`, minimises the number of calls to `dt` (only present in continuous time models...for now), and moves the logic about swapping between curr/next in the adjoint.  Fiddly despite the small size, but note no changes in any test code.

Make unfilter less coupled with discrete time model

---

R/interface-filter.R
R/interface-unfilter.R
R/tools.R
inst/include/dust2/r/continuous/filter.hpp
inst/include/dust2/r/continuous/unfilter.hpp
inst/include/dust2/r/discrete/filter.hpp
inst/include/dust2/r/discrete/unfilter.hpp
tests/testthat/test-filter.R
tests/testthat/test-tools.R

Merge after #82, contains those commits
This PR saves packer information into the likelihood objects so that they can be used with `dust_state_unpack`. Some more work is required here so that we can work with trajectories; these are indexed against state and so the packer would get involved twice.  However, with this PR we have the core information out that we would need at least.

Save packer information into likelihood (filter and unfilter)

---

R/interface.R
man/dust_system_create.Rd

Now that we have the "preserve dimension" bits in place, a single particle makes more sense and is nicer for odin

Change default number of particles

---

R/compile.R
R/interface.R
R/package.R
R/util.R
inst/template/dust.R
inst/template/package.R
tests/testthat/test-interface.R
tests/testthat/test-zzz-compile.R

This is something we fought against a bit in dust1/mcstate1, because when using callr we won't find code that we've loaded using `pkgload::load_all`.  This PR adds a slightly different bit of R code into the template for throwaway packages (created by `dust_compile`) compared with the more permanent ones created by `dust_compile`.  This means that if a user has done `dust_compile()` on a model and fed that into the callr runner for monty we will load the package namespace and everything should proceed fairly happily.
This is not a big problem for code where we have created a package, installed it and run monty from there.  We don't really solve this for the case where the user is developing a package and trying to use the callr runner; there we'll need them to install that package for …

Repair environment on load

---

DESCRIPTION
R/compile.R
man/dust_compile.Rd
tests/testthat/test-compile.R
vignettes/details.Rmd

Similar to #90, but for the debug argument (which affects only `dust_compile` and not `dust_package`)

Environment variable control over debug builds

---

DESCRIPTION
inst/include/dust2/common.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/test_helpers.cpp
tests/testthat/test-helpers.R

nothing like writing docs to flush this stuff out

Fix bugs in reading dimensions

---

DESCRIPTION
R/interface-likelihood.R
R/monty.R
inst/include/dust2/tools.hpp
man/dust_likelihood_monty.Rd
scripts/check_headers
tests/testthat/test-monty.R

This PR adds an observer interface to the dust/monty interface, using new features just added to monty.
The changes to check_headers are unrelated but due to a change in (I think) the C++ toolchain on the gha runners.

New observer interface

---

DESCRIPTION
inst/include/dust2/array.hpp
inst/include/dust2/common.hpp
inst/include/dust2/r/helpers.hpp

This PR will allow us, in odin, to write:
```
shared_type::dim_type dims;
```
and then fill in dimensions. We can't do this at the moment because we can't default-construct the dimensions, which this PR enables.  It also includes a `set()` method which we can use to set dimensions once we have them

Allow default construction of dimensions

---

R/data.R
tests/testthat/test-data.R
tests/testthat/test-monty.R

This PR allows groups to be named; it's debatable if we want integer valued groups because monty's grouped packer does not (yet) support that but with this change at least they agree on one way of recording groups!
Pretty minimal changes required here

Allow groups to be named

---

R/interface-continuous.R
inst/include/dust2/continuous/control.hpp
inst/include/dust2/continuous/solver.hpp
inst/include/dust2/r/continuous/control.hpp
man/dust_ode_control.Rd
tests/testthat/test-sirode.R

I reached the point where we need this in the odin-monty guide so figured it was an easy add.  Quite pleased with the relatively simple implementation here, using `std::upper_bound` to efficiently find the next relevant point and having a little extra loop within the main time loop.

Allow stopping at a vector of critical times

---

R/interface-filter.R
inst/include/dust2/filter.hpp
inst/include/dust2/r/continuous/filter.hpp
inst/include/dust2/r/discrete/filter.hpp
inst/include/dust2/r/filter.hpp
tests/testthat/helper-dust.R
tests/testthat/test-filter.R
tests/testthat/test-monty.R

Not long, but a bit of a battle.
This PR adds a second rng state to the filter to select the randomly selected particle.  This means that extracting trajectories from a filter does not affect the steps taken during sampling (which feels like it sticks closer to our general idea of being able to change runners/observers/etc without affecting samples taken).  This affects all the code that interacts with seeding, reading and writing the rng generators, and is generally a bit of a pain

Add extra rng state for selecting particle

---

inst/include/dust2/continuous/history.hpp
inst/include/dust2/continuous/solver.hpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/r/continuous/system.hpp

A bit of refactoring ahead of supporting delays.  This:
* moves history into its own file
* moves interpolation out of the solver and into the history class
* simplifies what we store in the internals
* moves the treatment of output to be more similar to that of rhs (using a private method)
* moves rhs (and output) to use non-static methods that take particle/group/thread as arguments
No changes to tests.

Refactor history internals

---

DESCRIPTION
inst/include/dust2/continuous/system.hpp

A bit of a disaster before that would have prevented running ODE systems in parallel.  This follows the same basic structure as internal, with `n_groups * n_threads` solvers

Add one solver per group&thread

---

DESCRIPTION
inst/include/dust2/continuous/delays.hpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/properties.hpp
tests/testthat/examples/delay.cpp
tests/testthat/test-zzz-compile.R

This PR works out if `rhs` or `output` will use delays and adds that as a property.  I could not work out how to make that a type, but have gone with a compile-time bool, which feels ok really.  This then removes the `rhs` and `output` argument from `delays` and makes the checks within `system` much nicer.
Merge after #127, contains those commits

Detect where delays are needed from system

---

DESCRIPTION
R/compile.R
inst/include/dust2/packing.hpp
inst/include/dust2/tools.hpp
tests/testthat/test-compile.R

This PR automatically computes offsets when creating a packing object in C++
It also sneaks in a couple of things for mrc-ide/odin2#123:
* add offset integer_sequence tool
* sanitise package names from classes containing an underscore

Store offset in packing

---

DESCRIPTION
inst/include/dust2/continuous/delays.hpp
inst/include/dust2/r/continuous/system.hpp
inst/include/dust2/r/helpers.hpp
tests/testthat/examples/delay.cpp
tests/testthat/test-zzz-compile.R

This PR changes (in a way that breaks the embryonic odin delay support) how we do most of the bookkeeping for delays, with a view to support the delayed expressions - where we have multiple delayed variables within a delayed group.
* Each delayed variable now gets an `offset` (from the parent state) and a `length`.  From that we can easily compute the index (the sequence `offset...(offset + length - 1)`) rather than having odin do that for us
* We then compute offsets from the delayed variable set
* Use of `std::move` in some headers is just to prevent some compiler warnings that were coming from a possible issue in cpp11's copy constructors. I'm forcing a move rather than a copy here to stop the warning appear!
Imagine we have a model packing vectors: `{A, B, C, D, E, F}`, with length …

More flexible delays

---

DESCRIPTION
inst/include/dust2/continuous/history.hpp
inst/include/dust2/continuous/solver.hpp
inst/include/dust2/packing.hpp
inst/include/dust2/r/continuous/system.hpp
tests/testthat/test-logistic.R

Small maintenance PR that will make #142 a bit easier to read.  This just adds t1 explicitly into the history, and separates out the step acceptance from updating interpolation coefficients

More explicit history time saving

---

.covrignore
.gitattributes
DESCRIPTION
R/interface.R
inst/include/dust2/common.hpp
inst/include/dust2/continuous/events.hpp
inst/include/dust2/continuous/history.hpp
inst/include/dust2/continuous/solver.hpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/properties.hpp
inst/include/dust2/r/continuous/system.hpp
inst/include/lostturnip.hpp
tests/testthat/examples/event.cpp
tests/testthat/helper-dust.R
tests/testthat/test-zzz-events.R

This PR is fairly large, but some of that is copying in the header from lostturnip (mrc-ide/lostturnip).
The idea is most easily seen in the deSolve docs: https://tpetzoldt.github.io/deSolve-forcing/deSolve-forcing.html - example 3 there.  Suppose we have some system where we want to apply a change to the state of the system when it exactly hits some state - in the included example this is where a bouncing ball hits the ground (`height = 0`) we want to invert and reduce its velocity (so `-v` becomes `v * 0.9`).
We do this by checking at the end of every step if a root is bounded, which occurs if the sign changes over the step.  Then we interpolate within that step using the ODE interpolation to find the time where the event happens and apply some "action" function.
The actions can only …

Simple event/root finding support

---

DESCRIPTION
inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/r/system.hpp

A long-forgotten PR; this sets the scene to allow different behaviour for simulation (run-and-save-history) for discrete time and continuous time models, eventually allowing an interpolation-based solution for continuous time models

Add basic simulate method into system objects

---

DESCRIPTION
R/interface-likelihood.R
R/monty.R
tests/testthat/test-zzz-restore.R

This PR fixes a long-standing issue that I kept fixing about - using the callr runner (or similar) with a likelihood that comes from a model compiled on-the-fly and not from a package.  This is because even though we can repair the pointer (#138), we don't cope with fixing the methods on the deserialised object.
`readRDS` load the object and sees references to the temporary package, can't find that, and then sets the environment to the global environment.  This is documented in `load`:
>      Objects can be saved with references to namespaces, usually as
>      part of the environment of a function or formula.  Such objects
>      can be loaded even if the namespace is not available: it is
>      replaced by a reference to the global environment with a warning.
>      The warning …

Allow callr to work with temporary models

---

DESCRIPTION
R/monty.R
tests/testthat/test-monty.R

Thanks for the example and pointer to the right bit of the logic @edknock - but it turns out that this is an issue with both packaged and non-packaged models (which I am happy about as I could not see how it was being triggered).  The issue comes if the filter has ever been initialised!  I've changed the logic around how we work out if the state index needs computing, after having worked out a failing example against the current version - see the added test which should fail for you and passes here.

Fix index of state when running a monty model

---

DESCRIPTION
inst/include/dust2/continuous/solver.hpp
tests/testthat/examples/event-time.cpp
tests/testthat/test-zzz-events.R

This PR fixes two bugs with event handling:
* events that happen on an exact time (a time that the solver will stop at) are now triggered
* if multiple events happen at the same exact time, their actions will both fire
Practically this only affects events that are written in terms of time.  I had thought that we'd need a second event type to support this, but the current approach is not bad to write (just accept no state) and no less efficient than something more bespoke.
There's a bit of complication now in tracking which events happen over a window that most of the time can be ignored (e.g., it's trivial in the case of a single event).

Support events that happen on times that are exactly hit

---

DESCRIPTION
inst/include/dust2/continuous/events.hpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/r/continuous/system.hpp
tests/testthat/examples/event-time.cpp
tests/testthat/examples/event.cpp
tests/testthat/test-zzz-events.R

Each event takes as its first argument a `std::string` with a name; at the point where we save out the internals we'll copy that into a character vector.  This is a breaking change to using events, as every event must include a name - it would be easy to make this have a default of `""` but then we have two args with defaults which makes for awkward construction in the absence of keyword arguments.

Add name metadata to event

---

DESCRIPTION
inst/include/dust2/continuous/events.hpp
inst/include/dust2/continuous/solver.hpp
inst/include/dust2/continuous/system.hpp
tests/testthat/examples/event-zero.cpp
tests/testthat/test-zzz-events.R

This was a partial solution to issues seen in daedalus - seen in https://github.com/jameel-institute/daedalus/pull/83
I don't think this was sufficient for a fix there, but it was certainly necessary.  The issue here is that the current version of event tracking assumes that the event changes state in such a way that the event is immediately impossible. We already exclude this possibility for events in time due to use of an inequality, but the current solution does not work for events that do not change a state variable.  In this case, the event can appear bracketed by the step immediately after the event, leading to the solver failing.
This fix keeps track of the last time an event fired and refuses to fire a second event at the exact same time.  This should work generally because …

Fix handling of events that do not alter variables

---

DESCRIPTION
R/interface-likelihood.R
tests/testthat/test-zzz-restore.R

Another iteration on a theme (see #149 and #138 for some of the previous attempts to fix this).
In #149 we introduced a check to find out if a on-the-fly model (generated with `dust_compile()`, possibly via `odin()`) had been serialised and restored but had lost its environment as a result. Unfortunately the fix there only worked for the stochastic models because we wired up methods using the `filter` element; this PR is a one line fix that gets the appropriate set of methods, allowing deserialisation to work correctly for the unfilter too.
The test here is a standalone version of the same problem as Ed originally observed and generates the same error (about `r_seed` being missing) when run against `main`
Closes #160

Fix restoration of transient unfilter
