mrc-ide/dust2

R/cpp11.R
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
src/cpp11.cpp
src/walk.cpp
tests/testthat/test-walk.R

~Merge after #3, contains those commits~
This PR allows updating parameters.  Some checks are not implemented yet, but this is enough for what we'll use in odin

Allow updating parameters

---

R/cpp11.R
inst/examples/sir.cpp
inst/examples/walk.cpp
inst/include/dust2/cpu.hpp
inst/include/dust2/r/cpu.hpp
inst/include/dust2/r/helpers.hpp
src/cpp11.cpp
src/sir.cpp
tests/testthat/test-sir.R
tests/testthat/test-walk.R

Pulled out of #8, this PR refactors parameter handling and does a couple of other little tidyups without changing functionality

Refactor parmeter handling

---

tests/testthat/test-zzz-openmp.R

One character fix - everything else fine

Fix condition on OpenMP test

---

DESCRIPTION
R/interface.R
inst/examples/logistic.cpp
inst/examples/sir.cpp
inst/examples/sirode.cpp
inst/examples/walk.cpp
inst/include/dust2/adjoint_data.hpp
inst/include/dust2/common.hpp
inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/packing.hpp
inst/include/dust2/r/continuous/system.hpp
inst/include/dust2/r/discrete/system.hpp
inst/include/dust2/r/helpers.hpp
inst/include/dust2/r/unfilter.hpp
inst/include/dust2/tools.hpp
inst/include/dust2/unfilter.hpp
src/logistic.cpp
src/sir.cpp
src/sirode.cpp
src/walk.cpp
tests/testthat/examples/openmp.cpp
tests/testthat/test-sir.R
tests/testthat/test-walk.R

I'd like to move this into mcstate at some point (so that it can interface nicely with the packer support there) but for now I'm working in dust as we can iterate more easily

Move to new packing helper

---

inst/examples/sir.cpp
inst/include/dust2/filter.hpp
inst/include/dust2/r/helpers.hpp
src/sir.cpp
tests/testthat/test-filter.R

Some more to do to enable this practically in odin, but this is the required bits to support doing the right thing in dust at least.  Reported by Ed when trying things out

Cope with missing data when running particle filter

---

R/cpp11.R
inst/include/dust2/interpolate/interpolate.hpp
inst/include/dust2/interpolate/spline.hpp
src/cpp11.cpp
src/test_interpolate.cpp
tests/testthat/test-interpolate.R

No new implementation - this does constant, linear and spline interpolation with no mutable state

Import intepolation code from dust1

---

R/mcstate.R
tests/testthat/test-mcstate.R

Small thing I noticed while trying to write some docs

Support mcstate2 wrapper with multiple parameter groups

---

inst/include/dust2/continuous/system.hpp
inst/include/dust2/discrete/system.hpp
inst/include/dust2/filter.hpp
inst/include/dust2/r/continuous/system.hpp
inst/include/dust2/r/discrete/filter.hpp
inst/include/dust2/r/discrete/system.hpp
inst/include/dust2/r/discrete/unfilter.hpp
inst/include/dust2/r/helpers.hpp
inst/include/dust2/r/system.hpp
inst/include/dust2/r/unfilter.hpp
src/test.cpp

This space intentionally left blank

Remove tabs

---

DESCRIPTION
R/data.R
tests/testthat/test-data.R

Fixes a problem in data processing found while getting a list column working with Thom

Allow list columns in filter data

---

DESCRIPTION
R/data.R
R/filter-support.R
R/interface.R
R/util.R
inst/include/dust2/r/helpers.hpp
inst/include/dust2/r/system.hpp
tests/testthat/test-filter-support.R
tests/testthat/test-logistic.R
tests/testthat/test-walk.R

~Merge after #65, contains those commits as I need both working with Thom~
Was previously forbidden, but actually well behaved now

Allow fractional time in simulate

---

DESCRIPTION
R/cpp11.R
inst/include/dust2/array.hpp
inst/include/dust2/common.hpp
src/cpp11.cpp
src/test_sum.cpp
tests/testthat/test-array.R

Previous version of this was generated in odin.dust: https://github.com/mrc-ide/odin.dust/blob/master/R/generate_dust_sexp.R#L111-L138 or here for the 1d version https://github.com/mrc-ide/odin/blob/master/inst/library.c#L297-L303

Add helpers for computing sums

---

.github/workflows/pkgdown.yaml
R/cpp11.R
inst/include/dust2/array.hpp
inst/include/dust2/r/helpers.hpp
scripts/bump_version
src/cpp11.cpp
src/test_helpers.cpp
tests/testthat/test-helpers.R
tests/testthat/test-logistic.R
tests/testthat/test-sir.R

We need these from odin2 to accept interesting arrays.
Also sneaking in two small maintenance tasks:
* only keep most recent gh-pages build
* copy bump_version script from monty

Add new array helpers

---

R/cpp11.R
inst/include/dust2/array.hpp
src/cpp11.cpp
src/test_sum.cpp
tests/testthat/test-array.R

Adds min and max alongside sum and prod

Some further reductions

---

inst/examples/logistic.cpp
inst/examples/sir.cpp
inst/examples/sirode.cpp
inst/examples/walk.cpp
src/logistic.cpp
src/sir.cpp
src/sirode.cpp
src/walk.cpp
tests/testthat/examples/openmp.cpp
tests/testthat/examples/zerotwice.cpp

This was never used, and so let's remove it

Drop update_internal

---

R/compile.R
R/package.R
R/util.R
man/dust_compile.Rd
man/dust_package.Rd
tests/testthat/test-compile.R
vignettes/details.Rmd

Merge after #89, contains those commits

Default control over 'quiet' argument

---

DESCRIPTION
inst/include/dust2/properties.hpp
tests/testthat/examples/internal.cpp
tests/testthat/test-zzz-slow.R

Fix crash using internal

---

DESCRIPTION
inst/include/dust2/r/helpers.hpp
tests/testthat/test-filter.R

Allow NAs within integers to be treated correctly

---

.covrignore
R/browser.R
R/interface-likelihood.R
R/interface.R
R/metadata.R
inst/examples/malaria.cpp
inst/include/dust2/trajectories.hpp
tests/testthat/helper-dust.R
tests/testthat/test-browser.R
tests/testthat/test-filter.R
tests/testthat/test-interface.R
tests/testthat/test-malaria.R
tests/testthat/test-metadata.R
tests/testthat/test-monty.R
tests/testthat/test-util.R
tests/testthat/test-walk.R

Tidies up some of the worst missing bits. More remains, though much if it is to do with adjoint models in ODE systems which are incompletely implemented at the moment

Improve coverage

---

inst/include/dust2/array.hpp
inst/include/dust2/common.hpp
inst/include/dust2/r/helpers.hpp

Adds hand-written 4d reduction, plus nicer compiler error for the rest.  **Also** sneaks in a little array reading helper

Support for 4d sums

---

DESCRIPTION
R/interface-unfilter.R
tests/testthat/test-monty.R

Was setup for filter but not unfilter in https://github.com/mrc-ide/dust2/pull/113

allow simple groups setup for unfilter

---

_pkgdown.yml
vignettes/migrating.Rmd

Was talking migration with Katy's guest and this felt useful

Basic migration guide

---

inst/include/dust2/common.hpp
inst/include/dust2/r/helpers.hpp

Some little helpers for checking if values fall within suitable ranges, these are used https://github.com/mrc-ide/odin2/pull/103

Add helpers for validating ranges

---

DESCRIPTION
inst/include/dust2/r/browser.hpp

Spotted sorting out browser from odin

Fix call to browser

---

DESCRIPTION
vignettes/writing.Rmd

In the writing section we don't actually show ode code, this PR fixes that.

Fix ode docs

---

DESCRIPTION
README.md

Ahead of the workshop, let's have fewer remotes-induced disasters

Better installation instructions
